@startuml

class TagFinance {
  - id: int
  - name: String
  - description: String
  + getAllTagFinance: List<TagFinance>
  + updateTagFinance: void
  + deleteTagFinance: void
  + getTagFinanceById(id: int): TagFinance
  + createTagFinance: void
}

class Transaction {
  - id: int
  - title: String
  - description: String
  - createdAt: Date
  - amount: double
  - tagId: int
  + getAllTransactions(): List<Transaction>
  + deleteTransaction(): void
  + updateTransaction(): void
  + createTransaction(): List<Transaction>
}

TagFinance "1" -- "*" Transaction: contains

@enduml
